import { Sidebar } from "@/components/layout/Sidebar";
import { HomePage } from "@/pages/Home";
import { 
  PRDGenerator, 
  UserStories, 
  ProblemRefiner, 
  FeaturePrioritizer, 
  SprintPlanner, 
  InterviewPrep 
} from "@/pages/Tools";
import ToolResultsHistory from "@/pages/ToolResultsHistory";
import { Switch, Route } from "wouter";
import { AlertTriangle } from "lucide-react";

export default function AppLayout() {
  return (
    <div className="flex h-screen bg-background overflow-hidden">
      <div className="flex-shrink-0">
        <Sidebar />
      </div>

      <main className="flex-1 flex flex-col min-w-0 overflow-auto">
        <div className="flex-1">
          <Switch>
            <Route path="/" component={HomePage} />
            <Route path="/tools/prd" component={PRDGenerator} />
            <Route path="/tools/user-stories" component={UserStories} />
            <Route path="/tools/problem-refiner" component={ProblemRefiner} />
            <Route path="/tools/prioritizer" component={FeaturePrioritizer} />
            <Route path="/tools/sprint-planner" component={SprintPlanner} />
            <Route path="/tools/interview-prep" component={InterviewPrep} />
            <Route path="/library/results" component={ToolResultsHistory} />
            <Route path="/:rest*" component={HomePage} />
          </Switch>
        </div>

        <footer className="border-t border-border px-6 py-3 flex items-center gap-2 text-xs text-muted-foreground bg-card/50 flex-shrink-0" data-testid="footer-ai-disclaimer">
          <AlertTriangle size={14} className="text-yellow-500 flex-shrink-0" />
          <span>AI-Generated Content: This content was generated by AI and may contain inaccuracies. Please review and edit before sharing.</span>
        </footer>
      </main>
    </div>
  );
}
